"""second

Revision ID: 3bd4208b15c6
Revises: 72a94494c142
Create Date: 2023-07-30 12:25:06.607877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bd4208b15c6'
down_revision = '72a94494c142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promt_histoty',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('promt', sa.Unicode(length=255), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('presentation_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promt_histoty')
    # ### end Alembic commands ###
