"""fifth

Revision ID: 60fc4ac8a3fd
Revises: 9a6423cf96e5
Create Date: 2023-08-20 15:48:47.429740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fc4ac8a3fd'
down_revision = '9a6423cf96e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('source', sa.Unicode(length=255), nullable=True),
        sa.Column('prompt', sa.Unicode(length=1024), nullable=False),
        sa.Column('resolution', sa.Unicode(length=255), nullable=False),
        sa.Column('type', sa.Unicode(length=255), nullable=False),
        sa.Column('path', sa.Unicode(length=255), nullable=False),
        sa.Column('create_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('slides', sa.Column('bgColor', sa.Unicode(length=255), nullable=True))
    op.add_column('slides', sa.Column('image_path', sa.Unicode(length=255), nullable=True))
    op.add_column('slides', sa.Column('image_background_path', sa.Unicode(length=255), nullable=True))
    op.drop_column('slides', 'subheader')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('subheader', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('slides', 'image_background_path')
    op.drop_column('slides', 'image_path')
    op.drop_column('slides', 'bgColor')
    op.drop_table('picture')
    # ### end Alembic commands ###
