"""First

Revision ID: 72a94494c142
Revises: 
Create Date: 2023-06-17 14:33:11.787726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72a94494c142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('password', sa.Unicode(length=255), nullable=False),
                    sa.Column('email', sa.Unicode(length=255), nullable=False),
                    sa.Column('username', sa.Unicode(length=255), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('presentations',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('title', sa.Unicode(length=255), nullable=True),
                    sa.Column('subject', sa.Unicode(length=255), nullable=True),
                    sa.Column('user_id', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('slides',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('header', sa.Unicode(length=255), nullable=True),
                    sa.Column('subheader', sa.Unicode(length=255), nullable=True),
                    sa.Column('paragraph', sa.Unicode(length=1024), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('presentation_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    op.drop_table('presentations')
    op.drop_table('users')
    # ### end Alembic commands ###
