"""change_table_name_seventh

Revision ID: 94308c623831
Revises: ffd86132f5d9
Create Date: 2023-09-09 18:10:59.390135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94308c623831'
down_revision = 'ffd86132f5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentation',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.Unicode(length=255), nullable=True),
        sa.Column('subject', sa.Unicode(length=255), nullable=True),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slide',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('header', sa.Unicode(length=255), nullable=True),
        sa.Column('bgColor', sa.Unicode(length=255), nullable=True),
        sa.Column('paragraph', sa.Unicode(length=1024), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('image_path', sa.Unicode(length=255), nullable=True),
        sa.Column('image_background_path', sa.Unicode(length=255), nullable=True),
        sa.Column('presentation_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['presentation_id'], ['presentation.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('prompt_history_presentation_id_fkey', 'prompt_history', type_='foreignkey')
    op.create_foreign_key("prompt_history_presentation_id_fkey", 'prompt_history', 'presentation', ['presentation_id'], ['id'])
    op.drop_table('slides')
    op.drop_table('presentations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentations',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='presentations_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='presentations_pkey')
    )
    op.create_table('slides',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('header', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('paragraph', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('presentation_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('bgColor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('image_background_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], name='slides_presentation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='slides_pkey')
    )
    op.drop_constraint("prompt_history_presentation_id_fkey", 'prompt_history', type_='foreignkey')
    op.create_foreign_key('prompt_history_presentation_id_fkey', 'prompt_history', 'presentations', ['presentation_id'], ['id'])
    op.drop_table('slide')
    op.drop_table('presentation')

    # ### end Alembic commands ###
