"""fourth

Revision ID: 9a6423cf96e5
Revises: 4d69091f5eb4
Create Date: 2023-08-08 19:32:57.123901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6423cf96e5'
down_revision = '4d69091f5eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('credits', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
